{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dextinity-site.fullname" . }}
  labels:
    {{- include "dextinity-site.labels" . | nindent 8 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
